# Generated by Django 3.0.6 on 2020-07-24 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0002_report_refund_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='critique',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CritiqueImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('critique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webb.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webb.Blog')),
            ],
        ),
    ]
