# Generated by Django 3.0.6 on 2020-07-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0006_auto_20200727_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable_crossover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_das',
            field=models.BooleanField(default=False),
        ),
    ]
