# Generated by Django 3.0.6 on 2020-07-30 08:55

from django.db import migrations, models
import webb.models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0007_auto_20200730_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(default=webb.models.get_today_date),
        ),
        migrations.AlterField(
            model_name='critique',
            name='created_at',
            field=models.DateField(default=webb.models.get_today_date),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=webb.models.get_today_date),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_date',
            field=models.DateField(default=webb.models.get_today_date),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateField(default=webb.models.get_today_date),
        ),
    ]
