# Generated by Django 3.0.6 on 2020-07-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0008_auto_20200730_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
