# Generated by Django 3.0.6 on 2020-07-31 02:21

import custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0009_auto_20200730_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, null=True, storage=custom_storage.BlogCritiqueCoverStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='critique',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, null=True, storage=custom_storage.BlogCritiqueCoverStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(storage=custom_storage.ProductStorage(), upload_to=''),
        ),
    ]
