# Generated by Django 3.0.6 on 2020-07-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0010_auto_20200731_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
