# Generated by Django 3.0.6 on 2020-07-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0011_auto_20200731_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blog',
            name='hashtags',
            field=models.ManyToManyField(to='webb.Hashtag'),
        ),
        migrations.AddField(
            model_name='critique',
            name='hashtags',
            field=models.ManyToManyField(to='webb.Hashtag'),
        ),
    ]
