# Generated by Django 3.0.6 on 2020-08-06 03:20

import custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0016_auto_20200806_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='bio_img',
            field=models.ImageField(storage=custom_storage.ProfileStorage(), upload_to=''),
        ),
    ]
