# Generated by Django 3.0.6 on 2020-08-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0018_auto_20200806_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
