# Generated by Django 3.0.6 on 2020-08-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0020_remove_product_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hide_from_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='critique',
            name='hide_from_profile',
            field=models.BooleanField(default=False),
        ),
    ]
