# Generated by Django 3.0.6 on 2020-08-13 01:45

from django.db import migrations, models
import django.db.models.deletion
import webb.models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0021_auto_20200807_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_spots', models.IntegerField(default=20)),
                ('products', models.ManyToManyField(to='webb.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=webb.models.get_today_date)),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to='webb.Profile')),
                ('following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following', to='webb.Profile')),
            ],
        ),
    ]
