# Generated by Django 3.0.6 on 2020-08-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0023_auto_20200818_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
