# Generated by Django 3.0.6 on 2020-08-24 06:58

from django.db import migrations, models
import django.db.models.deletion
import webb.models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0025_order_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateField(verbose_name=webb.models.get_today_date)),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_request_reason',
        ),
        migrations.AddField(
            model_name='product',
            name='formats',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profilefollowing',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to='webb.Creator'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webb.Order'),
        ),
    ]
